apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longsetup-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/matteoosh/argocd-long-setup-app 
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: longsetup

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

