apiVersion: v1
kind: Pod
metadata:
  labels:
    test: probes
  name: probes-exec
spec:
  containers:
  - name: probes-testing
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 30; touch /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      failureThreshold: 30
      periodSeconds: 10

