apiVersion: apps/v1
kind: Deployment
metadata:
  name:  long-setup-dep
  labels:
    app:  long-setup-dep
spec:
  selector:
    matchLabels:
      app: long-setup-dep
  replicas: 1
  template:
    metadata:
      labels:
        app:  long-setup-dep
    spec:
      containers:
      - name: probes-testing
        image: registry.k8s.io/busybox
        args:
        - /bin/sh
        - -c
        - sleep 30; touch /tmp/healthy; sleep 600
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 30
          periodSeconds: 10
